security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # api_key_user_provider:
        #     entity:
        #         class: App\Entity\User
        #         property: apiToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        tag:
            pattern: ^/tag/(\d+)
            anonymous: true
        forms:
            pattern: ^/(.+)
            logout: ~
            anonymous: false
            http_basic: true
        api:
            pattern: ^/api(.+)
            guard:
               authenticators:
                    - App\Security\TokenAuthenticator
        main:
            anonymous: true
            #
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            #form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^book/new, roles: ROLE_USER }
